In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/mamdouhsamir/fruit-weights/fruit-weights.csv
/kaggle/input/datasets/mamdouhsamir/right-triangles0/right-triangles0.csv

In [2]:
#Core Pandas Moves

#df.eval(): Does calculations.
#df.query(): Finds rows.
#df.groupby(): Builds groups of rows.

#DataFrame.eval()

import pandas as pd

df = pd.read_csv('/kaggle/input/datasets/mamdouhsamir/right-triangles0/right-triangles0.csv')

df['area'] = df.eval('0.5 * base * height')
df # display it

    color  base  height   area
0     red    15      18  135.0
1   green    30      10  150.0
2  yellow     8       5   20.0
3  orange    12      12   72.0
4    blue    22      13  143.0

In [3]:
#DataFrame.query()

yy = pd.read_csv('/kaggle/input/datasets/mamdouhsamir/right-triangles0/right-triangles0.csv')

#yy.query('base>15')

yy.query('base == base.min()')

    color  base  height
2  yellow     8       5

In [4]:
#DataFrame.groupby()

df = pd.read_csv('/kaggle/input/datasets/mamdouhsamir/fruit-weights/fruit-weights.csv')


df

        fruit  weight
0  strawberry      10
1      banana     118
2   pineapple     800
3  strawberry      11
4  strawberry      12
5   pineapple     900
6      banana     124
7  strawberry      13
8  strawberry      11
9      banana     131

In [5]:

#df = df.groupby('fruit')

#df.groupby('fruit').sum()

#groups['weight'].mean()

#groups = df.groupby('fruit')

#series = groups['weight'].mean()

#series.reset_index()

#or

df.groupby('fruit')['weight'].mean().reset_index()

        fruit      weight
0      banana  124.333333
1   pineapple  850.000000
2  strawberry   11.400000